import sqlite3

# Connect to the SQLite database
conn = sqlite3.connect('data/dictionary.db')

# Create a cursor object
cursor = conn.cursor()

# Insert data into the dictionary table
words_data = [
    ("abacus", "Abacus refers to an ancient calculating tool consisting of rows of movable beads."),
    ("ballet", "Ballet refers to a highly stylized form of dance that originated in the courts of Renaissance Italy."),
    ("cactus", "Cactus refers to a spiny plant adapted to arid conditions, typically found in deserts."),
    ("dolphin", "Dolphin refers to a highly intelligent aquatic mammal known for its playful behavior."),
    ("eclipse", "Eclipse refers to an astronomical event where one celestial body moves into the shadow of another."),
    ("fossil", "Fossil refers to the preserved remains or impressions of ancient organisms found in rocks."),
    ("galaxy", "Galaxy refers to a massive system of stars, gas, dust, and dark matter bound together by gravity."),
    ("harbor", "Harbor refers to a sheltered body of water where ships can dock safely."),
    ("igloo", "Igloo refers to a dome-shaped shelter made of snow, traditionally built by Inuit people."),
    ("jigsaw", "Jigsaw refers to a puzzle consisting of various pieces that fit together to form a complete picture."),
    ("kayak", "Kayak refers to a small, narrow watercraft propelled by a double-bladed paddle."),
    ("lighthouse", "Lighthouse refers to a tall structure with a light at the top, used as a navigational aid for maritime pilots."),
    ("mandolin", "Mandolin refers to a stringed musical instrument resembling a lute, typically played with a plectrum."),
    ("nectar", "Nectar refers to a sugary fluid secreted by plants to attract pollinating insects and birds."),
    ("orchid", "Orchid refers to a diverse and widespread family of flowering plants with blooms that are often colorful and fragrant."),
    ("pyramid", "Pyramid refers to a monumental structure with a square or triangular base and sloping sides that meet at a point at the top."),
    ("quartz", "Quartz refers to a hard, crystalline mineral composed of silicon and oxygen atoms."),
    ("rainbow", "Rainbow refers to an arc of colors visible in the sky, caused by the refraction, dispersion, and reflection of light in water droplets."),
    ("sphinx", "Sphinx refers to a mythical creature with the head of a human and the body of a lion."),
    ("telescope", "Telescope refers to an optical instrument used to observe distant objects, especially in astronomy."),
    ("umbrella", "Umbrella refers to a portable device used for protection against rain or sunlight."),
    ("vortex", "Vortex refers to a swirling mass of fluid or air, especially one in which the flow rotates around an axis."),
    ("whale", "Whale refers to a large marine mammal with a streamlined body and a horizontal tail fin."),
    ("xylophone", "Xylophone refers to a musical instrument made of wooden bars that are struck with mallets."),
    ("yawn", "Yawn refers to the involuntary opening of the mouth, typically due to tiredness or boredom."),
    ("zeppelin", "Zeppelin refers to a type of rigid airship named after its inventor, Count Ferdinand von Zeppelin."),
    ("accordion", "Accordion refers to a portable musical instrument with keys and bellows that produces sound as air is pushed or pulled."),
    ("bicycle", "Bicycle refers to a vehicle composed of two wheels held in a frame one behind the other, propelled by pedals and steered with handlebars."),
    ("calendar", "Calendar refers to a system for organizing and dividing time into days, weeks, months, and years."),
    ("dandelion", "Dandelion refers to a common yellow-flowered plant whose seed heads disperse in the wind."),
    ("elevator", "Elevator refers to a platform or compartment housed in a shaft for raising and lowering people or things to different floors or levels."),
    ("firefly", "Firefly refers to a type of beetle that emits light from its abdomen, creating a glowing effect."),
    ("giraffe", "Giraffe refers to a tall African mammal with a very long neck and legs."),
    ("hammock", "Hammock refers to a hanging bed made of canvas or netting, suspended by cords at the ends."),
    ("icicle", "Icicle refers to a spike of ice formed when water dripping or falling freezes."),
    ("jukebox", "Jukebox refers to a coin-operated machine that plays selected music from self-contained records or CDs."),
    ("koala", "Koala refers to a tree-dwelling marsupial native to Australia, known for its bear-like appearance and love of eucalyptus leaves."),
    ("lantern", "Lantern refers to a portable light source with a protective enclosure, typically containing a candle or a light bulb."),
    ("mushroom", "Mushroom refers to a fleshy, spore-bearing fruiting body of a fungus, typically produced above ground."),
    ("nebula", "Nebula refers to a cloud of gas and dust in space, often visible as a bright patch or dark silhouette."),
    ("octopus", "Octopus refers to a soft-bodied, eight-limbed mollusk known for its intelligence and ability to escape predators."),
    ("panther", "Panther refers to a large wild cat, also known as a leopard or cougar, depending on the region."),
    ("quiver", "Quiver refers to a container used for holding arrows, typically carried on the back or at the hip."),
    ("rainforest", "Rainforest refers to a dense, tropical forest with high rainfall and rich biodiversity."),
    ("sculpture", "Sculpture refers to the art of making three-dimensional forms or figures from materials such as stone, metal, or wood."),
    ("tornado", "Tornado refers to a rapidly rotating column of air extending from a thunderstorm to the ground, often causing severe damage."),
    ("unicorn", "Unicorn refers to a mythical animal typically represented as a horse with a single straight horn projecting from its forehead."),
    ("volcano", "Volcano refers to an opening in the Earth's crust through which molten lava, ash, and gases are ejected."),
    ("waterfall", "Waterfall refers to a steep descent of water from a height, especially a cascade of water over a precipice."),
    ("yacht", "Yacht refers to a medium-sized sailboat equipped for cruising or racing."),
    ("zucchini", "Zucchini refers to a summer squash that is typically dark green in color and used as a vegetable."),
    ("avalanche", "Avalanche refers to a mass of snow, ice, and rocks falling rapidly down a mountainside."),
    ("blizzard", "Blizzard refers to a severe snowstorm with strong winds and low visibility."),
    ("compass", "Compass refers to an instrument used for navigation and orientation that shows direction relative to the geographic cardinal directions."),
    ("dragonfly", "Dragonfly refers to a large, fast-flying insect with two pairs of strong transparent wings."),
    ("espresso", "Espresso refers to a strong coffee brewed by forcing steam through finely ground coffee beans."),
    ("fountain", "Fountain refers to a structure that sends water into the air in a decorative way."),
    ("gazelle", "Gazelle refers to a small, slender antelope that typically inhabits open plains in Africa and Asia."),
    ("horizon", "Horizon refers to the line at which the Earth's surface and the sky appear to meet."),
    ("iris", "Iris refers to a type of flowering plant, also the colored part of the eye surrounding the pupil."),
    ("jellyfish", "Jellyfish refers to a free-swimming marine animal with a gelatinous, umbrella-shaped body and trailing tentacles."),
    ("kiwi", "Kiwi refers to a flightless bird native to New Zealand, also a small, brown, fuzzy fruit with green flesh."),
    ("labyrinth", "Labyrinth refers to a complicated, irregular network of passages or paths in which it is difficult to find one's way."),
    ("meteor", "Meteor refers to a small body of matter from outer space that enters the Earth's atmosphere, appearing as a streak of light."),
    ("nocturnal", "Nocturnal refers to being active at night and asleep during the day."),
    ("obsidian", "Obsidian refers to a naturally occurring volcanic glass formed as an extrusive igneous rock."),
    ("peacock", "Peacock refers to a large bird known for its iridescent tail feathers with eye-like patterns."),
    ("quokka", "Quokka refers to a small marsupial native to Australia, known for its friendly appearance and smile-like expression."),
    ("raincoat", "Raincoat refers to a waterproof or water-resistant coat worn to protect the body from rain."),
    ("seahorse", "Seahorse refers to a small marine fish with a horse-like head and a curled tail."),
    ("trampoline", "Trampoline refers to a strong, flexible fabric stretched over a steel frame, used for jumping and acrobatics."),
    ("universe", "Universe refers to all existing matter and space considered as a whole, including galaxies, stars, and planets."),
    ("vulture", "Vulture refers to a large bird of prey that scavenges on dead animals."),
    ("windmill", "Windmill refers to a structure that converts wind power into rotational energy to drive machinery."),
    ("xenon", "Xenon refers to a colorless, dense, odorless noble gas found in the Earth's atmosphere in trace amounts."),
    ("yodel", "Yodel refers to a form of singing that involves rapid changes of pitch, typically between the chest and head voice."),
    ("zigzag", "Zigzag refers to a line or course that proceeds with sharp turns in alternating directions."),
    ("antelope", "Antelope refers to a swift-running deer-like animal with smooth hair and upward-pointing horns."),
    ("bamboo", "Bamboo refers to a giant woody grass that grows chiefly in the tropics and is used for building and crafts."),
    ("carousel", "Carousel refers to a rotating amusement ride with seats shaped like animals, usually horses."),
    ("daffodil", "Daffodil refers to a spring-flowering plant with yellow or white petals and a central trumpet-shaped corona."),
    ("easel", "Easel refers to a stand used by artists to hold a canvas upright while they paint."),
    ("falcon", "Falcon refers to a bird of prey with long pointed wings and a notched beak."),
    ("gondola", "Gondola refers to a narrow, flat-bottomed boat with a high point at both ends, traditionally used in Venice."),
    ("hurricane", "Hurricane refers to a powerful tropical storm with strong winds and heavy rain."),
    ("iguana", "Iguana refers to a large, herbivorous lizard native to Central and South America."),
    ("jungle", "Jungle refers to a dense, tropical forest with a large variety of plants and animals."),
    ("kangaroo", "Kangaroo refers to a large marsupial from Australia known for its powerful hind legs and jumping ability."),
    ("lantern", "Lantern refers to a portable light source with a protective enclosure, typically containing a candle or a light bulb."),
    ("mongoose", "Mongoose refers to a small carnivorous mammal known for its agility and ability to fight venomous snakes."),
    ("nectarine", "Nectarine refers to a smooth-skinned variety of peach with firm, juicy flesh."),
    ("ostrich", "Ostrich refers to the world's largest bird, native to Africa, known for its speed and flightless nature."),
    ("puzzle", "Puzzle refers to a game or problem that tests a person's ingenuity or knowledge."),
    ("quartz", "Quartz refers to a hard, crystalline mineral composed of silicon and oxygen atoms."),
    ("reef", "Reef refers to a ridge of jagged rock, coral, or sand just above or below the surface of the sea."),
    ("safari", "Safari refers to an expedition to observe or hunt animals in their natural habitat, especially in East Africa."),
    ("turtle", "Turtle refers to a reptile with a bony or cartilaginous shell, into which it can retract its head and limbs."),
    ("utensil", "Utensil refers to a tool, container, or other article, especially for household use."),
    ("valley", "Valley refers to a low area of land between hills or mountains, typically with a river or stream flowing through it."),
    ("wilderness", "Wilderness refers to an uncultivated, uninhabited, and inhospitable region."),
    ("xylophone", "Xylophone refers to a musical instrument made of wooden bars that are struck with mallets."),
    ("yarn", "Yarn refers to spun thread used for knitting, weaving, or sewing."),
    ("zinnia", "Zinnia refers to a genus of plants in the daisy family, known for their bright, colorful flowers."),
    ("ankle", "Ankle refers to the joint connecting the foot with the leg."),
    ("beacon", "Beacon refers to a light or other visible object serving as a signal, warning, or guide."),
    ("crater", "Crater refers to a large, bowl-shaped cavity in the ground or on a celestial object, typically caused by an explosion or the impact of a meteorite."),
    ("dagger", "Dagger refers to a short, pointed weapon with a sharp blade, used for stabbing."),
    ("emblem", "Emblem refers to a symbolic object used as a distinctive badge of a nation, organization, or family."),
    ("flute", "Flute refers to a woodwind instrument made from a tube with holes that are stopped by the fingers or keys."),
    ("goblet", "Goblet refers to a drinking glass with a foot and a stem."),
    ("helmet", "Helmet refers to a protective head covering made of hard material."),
    ("insect", "Insect refers to a small arthropod animal with six legs and generally one or two pairs of wings."),
    ("jet", "Jet refers to a high-speed stream of liquid or gas forced out of a small opening."),
    ("knapsack", "Knapsack refers to a bag with shoulder straps, carried on the back, and typically made of canvas or other weatherproof material."),
    ("lighthouse", "Lighthouse refers to a tall structure with a light at the top, used as a navigational aid for maritime pilots."),
    ("meteorite", "Meteorite refers to a piece of rock or metal that has fallen to the Earth's surface from outer space as a meteor."),
    ("nectar", "Nectar refers to a sugary fluid secreted by plants to attract pollinating insects and birds."),
    ("octopus", "Octopus refers to a soft-bodied, eight-limbed mollusk known for its intelligence and ability to escape predators."),
    ("pyramid", "Pyramid refers to a monumental structure with a square or triangular base and sloping sides that meet at a point at the top."),
    ("quilt", "Quilt refers to a warm bed covering made of padding enclosed between layers of fabric and kept in place by lines of stitching, typically applied in a decorative design."),
    ("rainbow", "Rainbow refers to an arc of colors visible in the sky, caused by the refraction, dispersion, and reflection of light in water droplets."),
    ("sphere", "Sphere refers to a perfectly round geometrical object in three-dimensional space, such as a ball."),
    ("telescope", "Telescope refers to an optical instrument used to observe distant objects, especially in astronomy."),
    ("umbrella", "Umbrella refers to a portable device used for protection against rain or sunlight."),
    ("vortex", "Vortex refers to a swirling mass of fluid or air, especially one in which the flow rotates around an axis."),
    ("whale", "Whale refers to a large marine mammal with a streamlined body and a horizontal tail fin."),
    ("xenon", "Xenon refers to a colorless, dense, odorless noble gas found in the Earth's atmosphere in trace amounts."),
    ("yawn", "Yawn refers to the involuntary opening of the mouth, typically due to tiredness or boredom."),
    ("zeppelin", "Zeppelin refers to a type of rigid airship named after its inventor, Count Ferdinand von Zeppelin."),
    ("archipelago", "Archipelago refers to a group of islands scattered across a body of water."),
    ("bonfire", "Bonfire refers to a large outdoor fire used as part of a celebration."),
    ("crystal", "Crystal refers to a solid material whose atoms are arranged in a highly ordered, repeating pattern."),
    ("dune", "Dune refers to a hill or ridge of sand piled up by the wind."),
    ("eruption", "Eruption refers to the act of a volcano expelling lava, ash, and gases."),
    ("falcon", "Falcon refers to a bird of prey with long pointed wings and a notched beak."),
    ("geyser", "Geyser refers to a hot spring in which water intermittently boils, sending a tall column of water and steam into the air."),
    ("harp", "Harp refers to a stringed musical instrument that is played by plucking the strings with the fingers."),
    ("icicle", "Icicle refers to a spike of ice formed when water dripping or falling freezes."),
    ("jaguar", "Jaguar refers to a large wild cat with a yellowish-brown coat marked with black spots, native to Central and South America."),
    ("kelp", "Kelp refers to a large brown seaweed that typically has a long, tough stalk."),
    ("lagoon", "Lagoon refers to a shallow body of water separated from a larger body of water by sandbars, barrier islands, or coral reefs."),
    ("monsoon", "Monsoon refers to a seasonal reversing wind accompanied by corresponding changes in precipitation."),
    ("nectarine", "Nectarine refers to a smooth-skinned variety of peach with firm, juicy flesh."),
    ("oasis", "Oasis refers to a fertile spot in a desert where water is found."),
    ("plaza", "Plaza refers to a public square, marketplace, or similar open space in a built-up area."),
    ("quasar", "Quasar refers to a massive and extremely remote celestial object that emits exceptionally large amounts of energy."),
    ("reef", "Reef refers to a ridge of jagged rock, coral, or sand just above or below the surface of the sea."),
    ("savanna", "Savanna refers to a grassy plain in tropical and subtropical regions, with few trees."),
    ("tundra", "Tundra refers to a vast, flat, treeless Arctic region in which the subsoil is permanently frozen."),
    ("uvula", "Uvula refers to the small, fleshy, conical projection hanging from the soft palate at the back of the throat."),
    ("viper", "Viper refers to a venomous snake with large hinged fangs, typically having a stout body with dark patterns."),
    ("walnut", "Walnut refers to a nut that has a wrinkled shell and a brown seed."),
    ("xenon", "Xenon refers to a colorless, dense, odorless noble gas found in the Earth's atmosphere in trace amounts."),
    ("yodel", "Yodel refers to a form of singing that involves rapid changes of pitch, typically between the chest and head voice."),
    ("zeppelin", "Zeppelin refers to a type of rigid airship named after its inventor, Count Ferdinand von Zeppelin."),
    ("avalanche", "Avalanche refers to a mass of snow, ice, and rocks falling rapidly down a mountainside."),
    ("bamboo", "Bamboo refers to a giant woody grass that grows chiefly in the tropics and is used for building and crafts."),
    ("caterpillar", "Caterpillar refers to the larval stage of a butterfly or moth."),
    ("dome", "Dome refers to a rounded vault forming the roof of a building or structure, typically with a circular base."),
    ("ember", "Ember refers to a small, glowing piece of coal or wood in a dying fire."),
    ("fjord", "Fjord refers to a long, narrow, deep inlet of the sea between high cliffs, typically formed by the submergence of a glaciated valley."),
    ("glacier", "Glacier refers to a slowly moving mass or river of ice formed by the accumulation and compaction of snow on mountains or near the poles."),
    ("horizon", "Horizon refers to the line at which the Earth's surface and the sky appear to meet."),
    ("island", "Island refers to a piece of land surrounded by water."),
    ("jungle", "Jungle refers to a dense, tropical forest with a large variety of plants and animals."),
    ("kayak", "Kayak refers to a small, narrow watercraft propelled by a double-bladed paddle."),
    ("lagoon", "Lagoon refers to a shallow body of water separated from a larger body of water by sandbars, barrier islands, or coral reefs."),
    ("mountain", "Mountain refers to a large natural elevation of the earth's surface rising abruptly from the surrounding level."),
    ("nebula", "Nebula refers to a cloud of gas and dust in space, often visible as a bright patch or dark silhouette."),
    ("ocean", "Ocean refers to a very large expanse of sea, in particular each of the main areas into which the sea is divided geographically."),
    ("plaza", "Plaza refers to a public square, marketplace, or similar open space in a built-up area."),
    ("quarry", "Quarry refers to a large, deep pit from which stone or other materials are extracted."),
    ("reef", "Reef refers to a ridge of jagged rock, coral, or sand just above or below the surface of the sea."),
    ("savanna", "Savanna refers to a grassy plain in tropical and subtropical regions, with few trees."),
    ("tundra", "Tundra refers to a vast, flat, treeless Arctic region in which the subsoil is permanently frozen."),
    ("unicorn", "Unicorn refers to a mythical animal typically represented as a horse with a single straight horn projecting from its forehead."),
    ("valley", "Valley refers to a low area of land between hills or mountains, typically with a river or stream flowing through it."),
    ("whale", "Whale refers to a large marine mammal with a streamlined body and a horizontal tail fin."),
    ("xerox", "Xerox refers to a brand name used to refer to a photocopy or the act of making a photocopy."),
    ("yacht", "Yacht refers to a medium-sized sailboat equipped for cruising or racing."),
    ("zephyr", "Zephyr refers to a gentle, mild breeze, especially one from the west."),
    ("arch", "Arch refers to a curved symmetrical structure spanning an opening and typically supporting the weight of a bridge, roof, or wall above it."),
    ("blizzard", "Blizzard refers to a severe snowstorm with strong winds and low visibility."),
    ("canyon", "Canyon refers to a deep gorge, typically one with a river flowing through it, as found in North America."),
    ("drought", "Drought refers to a prolonged period of abnormally low rainfall, leading to a shortage of water."),
    ("earthquake", "Earthquake refers to a sudden and violent shaking of the ground, sometimes causing great destruction, as a result of movements within the earth's crust or volcanic action."),
    ("flood", "Flood refers to an overflow of a large amount of water beyond its normal limits, especially over what is normally dry land."),
    ("geyser", "Geyser refers to a hot spring in which water intermittently boils, sending a tall column of water and steam into the air."),
    ("hurricane", "Hurricane refers to a powerful tropical storm with strong winds and heavy rain."),
    ("island", "Island refers to a piece of land surrounded by water."),
    ("jungle", "Jungle refers to a dense, tropical forest with a large variety of plants and animals."),
    ("karst", "Karst refers to a landscape underlain by limestone that has been eroded, producing ridges, towers, fissures, sinkholes, and other characteristic landforms."),
    ("lagoon", "Lagoon refers to a shallow body of water separated from a larger body of water by sandbars, barrier islands, or coral reefs."),
    ("mountain", "Mountain refers to a large natural elevation of the earth's surface rising abruptly from the surrounding level."),
    ("nebula", "Nebula refers to a cloud of gas and dust in space, often visible as a bright patch or dark silhouette."),
    ("oasis", "Oasis refers to a fertile spot in a desert where water is found."),
    ("pinnacle", "Pinnacle refers to the highest point of achievement, success, or fame."),
    ("quartz", "Quartz refers to a hard, crystalline mineral composed of silicon and oxygen atoms."),
    ("reef", "Reef refers to a ridge of jagged rock, coral, or sand just above or below the surface of the sea."),
    ("savanna", "Savanna refers to a grassy plain in tropical and subtropical regions, with few trees."),
    ("tundra", "Tundra refers to a vast, flat, treeless Arctic region in which the subsoil is permanently frozen."),
    ("uvula", "Uvula refers to the small, fleshy, conical projection hanging from the soft palate at the back of the throat."),
    ("vortex", "Vortex refers to a swirling mass of fluid or air, especially one in which the flow rotates around an axis."),
    ("whirlpool", "Whirlpool refers to a rapidly rotating mass of water in a river or sea into which objects may be drawn."),
    ("xerox", "Xerox refers to a brand name used to refer to a photocopy or the act of making a photocopy."),
    ("yacht", "Yacht refers to a medium-sized sailboat equipped for cruising or racing."),
    ("zephyr", "Zephyr refers to a gentle, mild breeze, especially one from the west.")
    # Continue adding more entries if needed
]

cursor.executemany('INSERT OR IGNORE INTO dictionary (word, meaning) VALUES (?, ?)', words_data)

# Commit the changes
conn.commit()

# Close the connection
conn.close()

print("Data inserted successfully, duplicates were skipped.")
